version: '3'

networks:
  app-network:
    driver: bridge

services:
  c3po_app:
    build:
      context: .docker/php
      dockerfile: Dockerfile
    container_name: c3po_app
    entrypoint: .docker/docker-entrypoint.sh
    restart: unless-stopped
    tty: true
    networks:
      - app-network
    working_dir: /var/www
    volumes:
      - ./:/var/www
    depends_on:
      - c3po_db
  c3po_db:
    image: mysql:5.7.37-oracle@sha256:1e755fd5ab6cd782256827067603dbef93493c4a91bbb88d51362dbf1f57e8b1
    command: --default-authentication-plugin=mysql_native_password
    container_name: c3po_db
    restart: unless-stopped
    tty: true
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: db_application
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - .docker/mysql:/var/lib/mysql
    networks:
      - app-network